# Generated by Django 4.2.7 on 2025-07-01 18:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum 200 characters', max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(help_text='Detailed project description', verbose_name='Project Description')),
                ('technologies', models.JSONField(blank=True, default=list, help_text="List of technologies used (e.g., ['Python', 'Django', 'React'])", verbose_name='Technologies')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Project budget in currency', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Budget')),
                ('deadline', models.DateField(blank=True, help_text='Expected project completion date', null=True, verbose_name='Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='JSON field for storing additional information', verbose_name='Additional Data')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Owner')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Vacancy Title')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('requirements', models.TextField(verbose_name='Requirements')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Minimum Salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Maximum Salary')),
                ('employment_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], default='full-time', max_length=50, verbose_name='Employment Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the vacancy is visible in search', verbose_name='Is Active')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-created_at'],
            },
        ),
    ]
